### ISSUE TITLE
Auto completion for references works only partially

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#23]
Auto completion of references using `->` `>` works only if the target element is coming from a single file. If the target is present in multiple files or in multiple folders, auto-completion works only till the folder listing (no files or IDs under the folders are offered) .

No errors are thrown.

**Comment by danwos** [comment]
How can a target need be present in multiple files?

Is this because of some sort of variant management, so that during build time only one need-target file gets used?
Or because of the use of needextend?

However, as this information is coming from ``need.json``, there data there must get misinterpreted by Open-Needs-IDE, or the data itself is already corrupted, then it's a bug in Sphinx-Needs.
Have to check this.

**Comment by danwos** [comment]
Example: 2 needs of type "req", one in "file_1.rst" and the other one in "file_2.rst". This is not supported.

**Comment by twodrops** [comment]
Yes, this is what I meant. You just need two "reqs" in two different files and not in the same file and the feature does not work

**Comment by twodrops** [comment]
I checked the needs and I can see that I have all the required needs present there. It must then be something else that is causing this. We can do some live testing with my example in our telco today :)

**Comment by haiyangToAI** [comment]
Hi @twodrops,

After thoroughly investigation, I finally identified the issue, which has nothing to do with auto completion or needls.

The auto completion issue you experienced is because needs.json not got loaded. The reason that needs.json not loaded is because it failed to load declared needs_types from conf.py.

The reason why it failed to load needs_types from conf.py is because:

- In the conf.py from sphinx-needs-basics, the user specified config for github needs_services, the code there expecting Github Enterprise credentials from environment variables.

This is also the reason why it works for me locally at the first place when I didn't test the sphinx-needs-basics repo.

Potential fix in the future might be to introduce another setting to get needs_types from conf.py.

**Comment by twodrops** [comment]
@haiyangToAI Thanks for finding out the root cause. I suppose it was not all that easy to come to that conclusion. Great!
I had reported a similar issue here https://github.com/open-needs/open-needs-ide/issues/24. I guess we need a general solution if conf.py is "reused" outside the context of sphinx-build by open-needs-ide.

**Comment by danwos** [comment]
Problem solved and `/` must be used to select sub-folders
