### ISSUE TITLE
no vsix file under releases

### ISSUE THREAD

**Issue by kapinnow** [open-needs/open-needs-ide#3]
The [installation documentation](https://open-needs.org/open-needs-ide/installation.html) asks to download some vsix file [from releases](https://github.com/open-needs/open-needs-ide/releases) but the location is empty.

In order to [build the vsix](https://open-needs.org/open-needs-ide/contribution.html) on one's own some prerequisites should be mentioned (e.g. installation of npm and then vsce, see https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

**Comment by danwos** [comment]
Ohh yes, the CI is not yet set up correctly.

There is a release right in the code:
https://github.com/open-needs/open-needs-ide/blob/main/sphinx-needs-ext-0.0.8.vsix

But for sure this will change for future. So I keep this issue open, until we have a correct documented place for our releases.

Thanks for reporting :+1:

**Comment by kapinnow** [comment]
The delivered release is outdated as it displays to be a "Bosch" and not an "Open-Needs" extension. Morover the version number in setup.py is still 0.0.7 which should read 0.0.8 instead. After fix and sucessfull rebuild of the vsix one gets one step further though there might be additional issues, that require investigation.

**Comment by danwos** [comment]
Thanks for the details and the investigation.
I will try to fix them this week.

**Comment by danwos** [comment]
for Python we should store the version under a ``versions.py`` file and import it for package and setup.py.

**Comment by danwos** [comment]
This should all be fixed now with https://github.com/open-needs/open-needs-ide/pull/10 and PRs before.

The VS Code extension is now available on the marketplace and should be installed from there.
Docs got updated.

A fix for version matching is also added. It's not nice, but it works.

In future I would create common releases for the VS Code extension and the needls server.
So that e.g. both have the version 0.1.4 and only this combination is supported.
This makes it quite easy and we do not need to maintain compatibility lists.
As the installation of extension and needls is automated for the user, I see no important drawbacks.

For testing, the default way of using an "Extension Host" is implemented.
Debugging, setting breakpoints, watching the logs all works and is documented on the contribution page.
Also the CI executes this already, so that tests can now be written and get automatically executed on each PR.

So I think this issue can be closed :)
