### ISSUE TITLE
feature: allow id generation to inherit title

### ISSUE THREAD

**Issue by kapinnow** [open-needs/open-needs-ide#39]
add an option to generate the id of a need from it's title instead of a hash value

> the generation shall simply remove all blanks from the title (or replace them by some option character)
> the generation may limit the id size to a given number of characters 
> the generation may add some configurable smaller hash at the end for uniqueness

**Comment by danwos** [comment]
Isn't this more an issue for https://github.com/useblocks/sphinxcontrib-needs?

**Comment by kapinnow** [comment]
yes and no - from the construction of sphinxcontrib you're right since it involves the definition of a need, however, as of today the needls server component generates the hash i.e. the concrete ids (and I already prototyped s.th.) inside open-needs-ide

**Comment by twodrops** [comment]
In general, I do not think that a hash-based id  (as available in the original open-needs IDE contribution) is user-friendly in the docs-as-code context. Some kind of a namespace based ID would be more useful I feel. An id generated out of the title could be a good offering for the user to either keep it or adjust it to a more useful one.

**Comment by twodrops** [comment]
In the long run, the ID generation could be handled by Open-Needs (which will have a more global view on the IDs)

**Comment by danwos** [comment]
Ahh, I see. 
Sorry, I haven't thought about the snippet and id-autogeneration feature of open-needs-ide itself.
I agree, that this makes sense and would be a great, helpful feature.

Maybe the whitespace handling should be configurable. E.g CamelCase, "_" instead of whitespace, id only based on the first 3 words, ... . I see a lot of different, project-specific scenarios here.

**Comment by haiyangToAI** [comment]
Ticket moved to Sphinx-Needs.
